Alert
theprogrammerinyou/ShivanshUI pull request #2
Opened 2022-02-01 17:40 UTC by theprogrammerinyou

Added alerts in component library

2022-02-15 17:45 UTC, adith-a-danthi requested changes
I've mentioned a few suggestions below. Apart from that looks good, clean code.

2022-02-15 17:45 UTC, adith-a-danthi commented on components/avatar/avatar.css
> +}
I think this class can be removed since it's being used with `avatar` which already has `border-radius: 50%`.

2022-02-15 17:45 UTC, adith-a-danthi commented on components/avatar/avatar.css
> +}
You can create CSS variables for the colors

2022-02-15 17:45 UTC, adith-a-danthi commented on components/alert/alert.css
> +}
You can variables for these colors

2022-02-15 17:45 UTC, adith-a-danthi commented on components/alert/alert.html
> +    <title>Document</title>
You can set the document title to the component name

2022-02-15 17:45 UTC, adith-a-danthi commented on css/spacing.css
> +}
These seem to be classes for `sizing` and not `spacing`

2022-02-15 17:45 UTC, adith-a-danthi commented on css/typography.css
> +}
I would suggest changing the class name to something easier to understand, maybe `2xl-para` or alternatively suggest `text-xl`, `text-lg`, etc as the naming style.

2022-02-15 17:55 UTC, theprogrammerinyou commented
Thank you for the PR review. All the suggested changes have been done.

2022-02-16 16:09 UTC, Hamdrive reviewed
Code looks good, would suggest to format code wherever possible

2022-02-17 18:31 UTC, merged