Input
theprogrammerinyou/ShivanshUI pull request #6
Opened 2022-02-02 18:13 UTC by theprogrammerinyou

Added input component to component library

2022-02-16 16:48 UTC, Shivanshsharma01 requested changes

2022-02-16 16:48 UTC, Shivanshsharma01 commented on components/input/input.css
> +    max-width: 500px;
Try using rem above 16px

2022-02-19 16:57 UTC, shuntzhere approved these changes
Codes are good, easy to understand.

2022-02-20 16:50 UTC, theprogrammerinyou commented
Improved code- done with 2 reviews closing this PR.

2022-02-20 16:50 UTC, closed without merging